### PR TITLE
Fixes the path to the .json schema in repo and adds simple command line utility to validate schemas

### PR DESCRIPTION
**Pull request by NHPatterson**
I was validating the schemas I generated and when using this repo, I found a few bugs. I've addressed them in this PR as well as adding a command line utility to validate schemas. If provided a directory, the utility will assume this is the `raw` directory of the CODEX submission and look for the `experiment.json` file there. If provided a file path to a file ending with `.json`, it will read this file and attempt to validate.

This helped in validating our metadata files generated entirely outside of Akoya.

### CODE REVIEW

**Comment by VasylVaskivskyi** [comment]
Hi @NHPatterson, I see that you resolved the confusion about files with Matt. 
Sorry about that😅.
So, as far as I understand, we don't need to add the validation for the `experiment.json`  that you provided, but the fix for the filenames will be helpful.

**Review by VasylVaskivskyi — APPROVED** [review]

**Review by VasylVaskivskyi — CHANGES_REQUESTED** [review]
Is this still necessary?

**Review by VasylVaskivskyi — DISMISSED** [review]
Is this still necessary?

**Comment by VasylVaskivskyi** [comment]
I don't want to bother you with cherry picking necessary commit. I will just close this PR  and add changes myself

**Comment by NHPatterson** [comment]
@VasylVaskivskyi No worries. The reason to add the command line script is if someone else is in my situation, they can more easily validate that what they have generated passes validation, but it's probably not a big deal given the small potential user base.

**Pull request closed without merging**
